[build]
builder = "dockerfile"
watchPatterns = ["src/**", "public/**", "package.json", "package-lock.json", "vite.config.js", "tsconfig.json", "Dockerfile"]

[deploy]
restartPolicyType = "on_failure"
