[build]
builder = "NIXPACKS"
buildCommand = "go build -o server ./cmd/server/"
watchPatterns = ["cmd/**", "internal/**", "pkg/**", "go.mod", "go.sum"]

[deploy]
startCommand = "./server"
restartPolicyType = "on_failure"
