// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: family/v1/family.proto

package familyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "expenses-backend/pkg/family/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FamilySettingsServiceName is the fully-qualified name of the FamilySettingsService service.
	FamilySettingsServiceName = "family.v1.FamilySettingsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FamilySettingsServiceCreateFamilySettingProcedure is the fully-qualified name of the
	// FamilySettingsService's CreateFamilySetting RPC.
	FamilySettingsServiceCreateFamilySettingProcedure = "/family.v1.FamilySettingsService/CreateFamilySetting"
	// FamilySettingsServiceListFamilySettingsProcedure is the fully-qualified name of the
	// FamilySettingsService's ListFamilySettings RPC.
	FamilySettingsServiceListFamilySettingsProcedure = "/family.v1.FamilySettingsService/ListFamilySettings"
	// FamilySettingsServiceUpdateFamilySettingProcedure is the fully-qualified name of the
	// FamilySettingsService's UpdateFamilySetting RPC.
	FamilySettingsServiceUpdateFamilySettingProcedure = "/family.v1.FamilySettingsService/UpdateFamilySetting"
	// FamilySettingsServiceDeleteFamilySettingProcedure is the fully-qualified name of the
	// FamilySettingsService's DeleteFamilySetting RPC.
	FamilySettingsServiceDeleteFamilySettingProcedure = "/family.v1.FamilySettingsService/DeleteFamilySetting"
)

// FamilySettingsServiceClient is a client for the family.v1.FamilySettingsService service.
type FamilySettingsServiceClient interface {
	CreateFamilySetting(context.Context, *connect.Request[v1.CreateFamilySettingRequest]) (*connect.Response[v1.CreateFamilySettingResponse], error)
	ListFamilySettings(context.Context, *connect.Request[v1.ListFamilySettingsRequest]) (*connect.Response[v1.ListFamilySettingsResponse], error)
	UpdateFamilySetting(context.Context, *connect.Request[v1.UpdateFamilySettingRequest]) (*connect.Response[v1.UpdateFamilySettingResponse], error)
	DeleteFamilySetting(context.Context, *connect.Request[v1.DeleteFamilySettingRequest]) (*connect.Response[v1.DeleteFamilySettingResponse], error)
}

// NewFamilySettingsServiceClient constructs a client for the family.v1.FamilySettingsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFamilySettingsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FamilySettingsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	familySettingsServiceMethods := v1.File_family_v1_family_proto.Services().ByName("FamilySettingsService").Methods()
	return &familySettingsServiceClient{
		createFamilySetting: connect.NewClient[v1.CreateFamilySettingRequest, v1.CreateFamilySettingResponse](
			httpClient,
			baseURL+FamilySettingsServiceCreateFamilySettingProcedure,
			connect.WithSchema(familySettingsServiceMethods.ByName("CreateFamilySetting")),
			connect.WithClientOptions(opts...),
		),
		listFamilySettings: connect.NewClient[v1.ListFamilySettingsRequest, v1.ListFamilySettingsResponse](
			httpClient,
			baseURL+FamilySettingsServiceListFamilySettingsProcedure,
			connect.WithSchema(familySettingsServiceMethods.ByName("ListFamilySettings")),
			connect.WithClientOptions(opts...),
		),
		updateFamilySetting: connect.NewClient[v1.UpdateFamilySettingRequest, v1.UpdateFamilySettingResponse](
			httpClient,
			baseURL+FamilySettingsServiceUpdateFamilySettingProcedure,
			connect.WithSchema(familySettingsServiceMethods.ByName("UpdateFamilySetting")),
			connect.WithClientOptions(opts...),
		),
		deleteFamilySetting: connect.NewClient[v1.DeleteFamilySettingRequest, v1.DeleteFamilySettingResponse](
			httpClient,
			baseURL+FamilySettingsServiceDeleteFamilySettingProcedure,
			connect.WithSchema(familySettingsServiceMethods.ByName("DeleteFamilySetting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// familySettingsServiceClient implements FamilySettingsServiceClient.
type familySettingsServiceClient struct {
	createFamilySetting *connect.Client[v1.CreateFamilySettingRequest, v1.CreateFamilySettingResponse]
	listFamilySettings  *connect.Client[v1.ListFamilySettingsRequest, v1.ListFamilySettingsResponse]
	updateFamilySetting *connect.Client[v1.UpdateFamilySettingRequest, v1.UpdateFamilySettingResponse]
	deleteFamilySetting *connect.Client[v1.DeleteFamilySettingRequest, v1.DeleteFamilySettingResponse]
}

// CreateFamilySetting calls family.v1.FamilySettingsService.CreateFamilySetting.
func (c *familySettingsServiceClient) CreateFamilySetting(ctx context.Context, req *connect.Request[v1.CreateFamilySettingRequest]) (*connect.Response[v1.CreateFamilySettingResponse], error) {
	return c.createFamilySetting.CallUnary(ctx, req)
}

// ListFamilySettings calls family.v1.FamilySettingsService.ListFamilySettings.
func (c *familySettingsServiceClient) ListFamilySettings(ctx context.Context, req *connect.Request[v1.ListFamilySettingsRequest]) (*connect.Response[v1.ListFamilySettingsResponse], error) {
	return c.listFamilySettings.CallUnary(ctx, req)
}

// UpdateFamilySetting calls family.v1.FamilySettingsService.UpdateFamilySetting.
func (c *familySettingsServiceClient) UpdateFamilySetting(ctx context.Context, req *connect.Request[v1.UpdateFamilySettingRequest]) (*connect.Response[v1.UpdateFamilySettingResponse], error) {
	return c.updateFamilySetting.CallUnary(ctx, req)
}

// DeleteFamilySetting calls family.v1.FamilySettingsService.DeleteFamilySetting.
func (c *familySettingsServiceClient) DeleteFamilySetting(ctx context.Context, req *connect.Request[v1.DeleteFamilySettingRequest]) (*connect.Response[v1.DeleteFamilySettingResponse], error) {
	return c.deleteFamilySetting.CallUnary(ctx, req)
}

// FamilySettingsServiceHandler is an implementation of the family.v1.FamilySettingsService service.
type FamilySettingsServiceHandler interface {
	CreateFamilySetting(context.Context, *connect.Request[v1.CreateFamilySettingRequest]) (*connect.Response[v1.CreateFamilySettingResponse], error)
	ListFamilySettings(context.Context, *connect.Request[v1.ListFamilySettingsRequest]) (*connect.Response[v1.ListFamilySettingsResponse], error)
	UpdateFamilySetting(context.Context, *connect.Request[v1.UpdateFamilySettingRequest]) (*connect.Response[v1.UpdateFamilySettingResponse], error)
	DeleteFamilySetting(context.Context, *connect.Request[v1.DeleteFamilySettingRequest]) (*connect.Response[v1.DeleteFamilySettingResponse], error)
}

// NewFamilySettingsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFamilySettingsServiceHandler(svc FamilySettingsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	familySettingsServiceMethods := v1.File_family_v1_family_proto.Services().ByName("FamilySettingsService").Methods()
	familySettingsServiceCreateFamilySettingHandler := connect.NewUnaryHandler(
		FamilySettingsServiceCreateFamilySettingProcedure,
		svc.CreateFamilySetting,
		connect.WithSchema(familySettingsServiceMethods.ByName("CreateFamilySetting")),
		connect.WithHandlerOptions(opts...),
	)
	familySettingsServiceListFamilySettingsHandler := connect.NewUnaryHandler(
		FamilySettingsServiceListFamilySettingsProcedure,
		svc.ListFamilySettings,
		connect.WithSchema(familySettingsServiceMethods.ByName("ListFamilySettings")),
		connect.WithHandlerOptions(opts...),
	)
	familySettingsServiceUpdateFamilySettingHandler := connect.NewUnaryHandler(
		FamilySettingsServiceUpdateFamilySettingProcedure,
		svc.UpdateFamilySetting,
		connect.WithSchema(familySettingsServiceMethods.ByName("UpdateFamilySetting")),
		connect.WithHandlerOptions(opts...),
	)
	familySettingsServiceDeleteFamilySettingHandler := connect.NewUnaryHandler(
		FamilySettingsServiceDeleteFamilySettingProcedure,
		svc.DeleteFamilySetting,
		connect.WithSchema(familySettingsServiceMethods.ByName("DeleteFamilySetting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/family.v1.FamilySettingsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FamilySettingsServiceCreateFamilySettingProcedure:
			familySettingsServiceCreateFamilySettingHandler.ServeHTTP(w, r)
		case FamilySettingsServiceListFamilySettingsProcedure:
			familySettingsServiceListFamilySettingsHandler.ServeHTTP(w, r)
		case FamilySettingsServiceUpdateFamilySettingProcedure:
			familySettingsServiceUpdateFamilySettingHandler.ServeHTTP(w, r)
		case FamilySettingsServiceDeleteFamilySettingProcedure:
			familySettingsServiceDeleteFamilySettingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFamilySettingsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFamilySettingsServiceHandler struct{}

func (UnimplementedFamilySettingsServiceHandler) CreateFamilySetting(context.Context, *connect.Request[v1.CreateFamilySettingRequest]) (*connect.Response[v1.CreateFamilySettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("family.v1.FamilySettingsService.CreateFamilySetting is not implemented"))
}

func (UnimplementedFamilySettingsServiceHandler) ListFamilySettings(context.Context, *connect.Request[v1.ListFamilySettingsRequest]) (*connect.Response[v1.ListFamilySettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("family.v1.FamilySettingsService.ListFamilySettings is not implemented"))
}

func (UnimplementedFamilySettingsServiceHandler) UpdateFamilySetting(context.Context, *connect.Request[v1.UpdateFamilySettingRequest]) (*connect.Response[v1.UpdateFamilySettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("family.v1.FamilySettingsService.UpdateFamilySetting is not implemented"))
}

func (UnimplementedFamilySettingsServiceHandler) DeleteFamilySetting(context.Context, *connect.Request[v1.DeleteFamilySettingRequest]) (*connect.Response[v1.DeleteFamilySettingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("family.v1.FamilySettingsService.DeleteFamilySetting is not implemented"))
}
