// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: transaction/v1/transaction.proto

package transactionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Organization) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Posted        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=posted,proto3" json:"posted,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TransactedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transacted_at,json=transactedAt,proto3,oneof" json:"transacted_at,omitempty"`
	Pending       *bool                  `protobuf:"varint,6,opt,name=pending,proto3,oneof" json:"pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetPosted() *timestamppb.Timestamp {
	if x != nil {
		return x.Posted
	}
	return nil
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetTransactedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactedAt
	}
	return nil
}

func (x *Transaction) GetPending() bool {
	if x != nil && x.Pending != nil {
		return *x.Pending
	}
	return false
}

type Account struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Org              *Organization          `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance          string                 `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance *string                `protobuf:"bytes,6,opt,name=available_balance,json=availableBalance,proto3,oneof" json:"available_balance,omitempty"`
	BalanceDate      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=balance_date,json=balanceDate,proto3" json:"balance_date,omitempty"`
	Transactions     []*Transaction         `protobuf:"bytes,8,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetOrg() *Organization {
	if x != nil {
		return x.Org
	}
	return nil
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetAvailableBalance() string {
	if x != nil && x.AvailableBalance != nil {
		return *x.AvailableBalance
	}
	return ""
}

func (x *Account) GetBalanceDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BalanceDate
	}
	return nil
}

func (x *Account) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{3}
}

type GetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsResponse) Reset() {
	*x = GetAccountsResponse{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsResponse) ProtoMessage() {}

func (x *GetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_transaction_v1_transaction_proto protoreflect.FileDescriptor

const file_transaction_v1_transaction_proto_rawDesc = "" +
	"\n" +
	" transaction/v1/transaction.proto\x12\x0etransaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\fOrganization\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8e\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06posted\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06posted\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12D\n" +
	"\rtransacted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ftransactedAt\x88\x01\x01\x12\x1d\n" +
	"\apending\x18\x06 \x01(\bH\x01R\apending\x88\x01\x01B\x10\n" +
	"\x0e_transacted_atB\n" +
	"\n" +
	"\b_pending\"\xdb\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x03org\x18\x02 \x01(\v2\x1c.transaction.v1.OrganizationR\x03org\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x120\n" +
	"\x11available_balance\x18\x06 \x01(\tH\x00R\x10availableBalance\x88\x01\x01\x12=\n" +
	"\fbalance_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vbalanceDate\x12?\n" +
	"\ftransactions\x18\b \x03(\v2\x1b.transaction.v1.TransactionR\ftransactionsB\x14\n" +
	"\x12_available_balance\"\x14\n" +
	"\x12GetAccountsRequest\"J\n" +
	"\x13GetAccountsResponse\x123\n" +
	"\baccounts\x18\x01 \x03(\v2\x17.transaction.v1.AccountR\baccounts2l\n" +
	"\x12TransactionService\x12V\n" +
	"\vGetAccounts\x12\".transaction.v1.GetAccountsRequest\x1a#.transaction.v1.GetAccountsResponseB3Z1expenses-backend/pkg/transaction/v1;transactionv1b\x06proto3"

var (
	file_transaction_v1_transaction_proto_rawDescOnce sync.Once
	file_transaction_v1_transaction_proto_rawDescData []byte
)

func file_transaction_v1_transaction_proto_rawDescGZIP() []byte {
	file_transaction_v1_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)))
	})
	return file_transaction_v1_transaction_proto_rawDescData
}

var file_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transaction_v1_transaction_proto_goTypes = []any{
	(*Organization)(nil),          // 0: transaction.v1.Organization
	(*Transaction)(nil),           // 1: transaction.v1.Transaction
	(*Account)(nil),               // 2: transaction.v1.Account
	(*GetAccountsRequest)(nil),    // 3: transaction.v1.GetAccountsRequest
	(*GetAccountsResponse)(nil),   // 4: transaction.v1.GetAccountsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_transaction_v1_transaction_proto_depIdxs = []int32{
	5, // 0: transaction.v1.Transaction.posted:type_name -> google.protobuf.Timestamp
	5, // 1: transaction.v1.Transaction.transacted_at:type_name -> google.protobuf.Timestamp
	0, // 2: transaction.v1.Account.org:type_name -> transaction.v1.Organization
	5, // 3: transaction.v1.Account.balance_date:type_name -> google.protobuf.Timestamp
	1, // 4: transaction.v1.Account.transactions:type_name -> transaction.v1.Transaction
	2, // 5: transaction.v1.GetAccountsResponse.accounts:type_name -> transaction.v1.Account
	3, // 6: transaction.v1.TransactionService.GetAccounts:input_type -> transaction.v1.GetAccountsRequest
	4, // 7: transaction.v1.TransactionService.GetAccounts:output_type -> transaction.v1.GetAccountsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_transaction_v1_transaction_proto_init() }
func file_transaction_v1_transaction_proto_init() {
	if File_transaction_v1_transaction_proto != nil {
		return
	}
	file_transaction_v1_transaction_proto_msgTypes[1].OneofWrappers = []any{}
	file_transaction_v1_transaction_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_v1_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_v1_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_v1_transaction_proto_msgTypes,
	}.Build()
	File_transaction_v1_transaction_proto = out.File
	file_transaction_v1_transaction_proto_goTypes = nil
	file_transaction_v1_transaction_proto_depIdxs = nil
}
