// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package familydb

import (
	"time"
)

type Account struct {
	ID          int64  `json:"id"`
	AccountID   string `json:"account_id"`
	Name        string `json:"name"`
	SimplefinID int64  `json:"simplefin_id"`
}

type Category struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Color       *string   `json:"color"`
	Icon        *string   `json:"icon"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Expense struct {
	ID            int64     `json:"id"`
	CategoryID    *int64    `json:"category_id"`
	Amount        float64   `json:"amount"`
	Name          string    `json:"name"`
	DayOfMonthDue int64     `json:"day_of_month_due"`
	IsAutopay     bool      `json:"is_autopay"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type FamilyMember struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
	IsActive *bool     `json:"is_active"`
}

type FamilySetting struct {
	ID           int64   `json:"id"`
	SettingKey   string  `json:"setting_key"`
	SettingValue *string `json:"setting_value"`
	DataType     string  `json:"data_type"`
}

type SchemaMigration struct {
	Version         int64      `json:"version"`
	Name            string     `json:"name"`
	Filename        string     `json:"filename"`
	Description     *string    `json:"description"`
	AppliedAt       *time.Time `json:"applied_at"`
	Checksum        *string    `json:"checksum"`
	ExecutionTimeMs *int64     `json:"execution_time_ms"`
	MigrationType   *string    `json:"migration_type"`
	AppliedBy       *string    `json:"applied_by"`
}

type Transaction struct {
	ID          int64     `json:"id"`
	AccountID   int64     `json:"account_id"`
	PostedDate  time.Time `json:"posted_date"`
	Description string    `json:"description"`
	Payee       string    `json:"payee"`
}
