// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package familydb

import (
	"time"
)

type Category struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Color       *string   `json:"color"`
	Icon        *string   `json:"icon"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Expense struct {
	ID            string    `json:"id"`
	CategoryID    *string   `json:"category_id"`
	Amount        float64   `json:"amount"`
	Name          string    `json:"name"`
	DayOfMonthDue int64     `json:"day_of_month_due"`
	IsAutopay     bool      `json:"is_autopay"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type FamilyMember struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
	IsActive *bool     `json:"is_active"`
}

type SchemaMigration struct {
	Version         int64      `json:"version"`
	Name            string     `json:"name"`
	Filename        string     `json:"filename"`
	Description     *string    `json:"description"`
	AppliedAt       *time.Time `json:"applied_at"`
	Checksum        *string    `json:"checksum"`
	ExecutionTimeMs *int64     `json:"execution_time_ms"`
	MigrationType   *string    `json:"migration_type"`
	AppliedBy       *string    `json:"applied_by"`
}
