// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package familydb

import (
	"context"
)

type Querier interface {
	CountExpenses(ctx context.Context) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (*Category, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (*Expense, error)
	CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) (*FamilyMember, error)
	DeactivateFamilyMember(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	DeleteExpense(ctx context.Context, id string) error
	DeleteFamilyMember(ctx context.Context, id string) error
	GetCategoryByID(ctx context.Context, id string) (*Category, error)
	GetExpenseByID(ctx context.Context, id string) (*Expense, error)
	GetExpensesByDateRange(ctx context.Context, arg GetExpensesByDateRangeParams) ([]*Expense, error)
	GetFamilyMemberByEmail(ctx context.Context, email string) (*FamilyMember, error)
	GetFamilyMemberByID(ctx context.Context, id string) (*FamilyMember, error)
	ListAllFamilyMembers(ctx context.Context) ([]*FamilyMember, error)
	ListCategories(ctx context.Context) ([]*Category, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]*Expense, error)
	ListExpensesByCategory(ctx context.Context, categoryID *string) ([]*Expense, error)
	ListFamilyMembers(ctx context.Context) ([]*FamilyMember, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (*Category, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (*Expense, error)
	UpdateFamilyMember(ctx context.Context, arg UpdateFamilyMemberParams) (*FamilyMember, error)
}

var _ Querier = (*Queries)(nil)
