name: Build and Push Docker Images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: meta
        run: |
          # Extract version from tag (v1.2.3 -> 1.2.3)
          VERSION="${{ github.ref_name }}"
          if [[ $VERSION == v* ]]; then
            VERSION="${VERSION#v}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "backend_tags=ghcr.io/${{ github.repository }}/backend:${VERSION},ghcr.io/${{ github.repository }}/backend:latest" >> $GITHUB_OUTPUT
          echo "frontend_tags=ghcr.io/${{ github.repository }}/frontend:${VERSION},ghcr.io/${{ github.repository }}/frontend:latest" >> $GITHUB_OUTPUT

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.backend_tags }}
          labels: |
            org.opencontainers.image.title=Expenses Backend
            org.opencontainers.image.description=Go backend for expenses application
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.frontend_tags }}
          labels: |
            org.opencontainers.image.title=Expenses Frontend
            org.opencontainers.image.description=React frontend for expenses application
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Output image information
        run: |
          echo "✅ Built and pushed version: ${{ steps.meta.outputs.version }}"
          echo "Backend: ${{ steps.meta.outputs.backend_tags }}"
          echo "Frontend: ${{ steps.meta.outputs.frontend_tags }}"