name: Deploy to Development

on:
  push:
    branches: [ dev, develop ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'deploy/terraform/**'
      - '.github/workflows/deploy-dev.yml'

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Terraform Init
        run: terraform init
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Terraform Plan
        run: terraform plan -var-file="../environments/dev.tfvars" -out=tfplan
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DEV_DB_PASSWORD }}
          
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Output Deployment URLs
        run: terraform output
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}