name: Terraform Check

on:
  pull_request:
    paths:
      - 'deploy/terraform/**'
      - '.github/workflows/terraform-check.yml'

jobs:
  terraform-check:
    name: Terraform Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: deploy/terraform
        
      - name: Terraform Init
        run: terraform init
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Terraform Validate
        run: terraform validate
        working-directory: deploy/terraform
        
      - name: Terraform Plan (Dev)
        run: terraform plan -var-file="../environments/dev.tfvars" -no-color
        working-directory: deploy/terraform
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          TF_VAR_db_password: ${{ secrets.DEV_DB_PASSWORD }}
        continue-on-error: true
        
      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `### Terraform Plan Results
            
            #### Terraform Format and Style 🖌
            \`${{ steps.fmt.outcome }}\`
            
            #### Terraform Initialization ⚙️
            \`${{ steps.init.outcome }}\`
            
            #### Terraform Validation 🤖
            \`${{ steps.validate.outcome }}\`
            
            #### Terraform Plan 📖
            \`${{ steps.plan.outcome }}\`
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })