// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package masterdb

import (
	"time"
)

type Family struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	InviteCode    string    `json:"invite_code"`
	DatabaseUrl   string    `json:"database_url"`
	ManagerID     string    `json:"manager_id"`
	SchemaVersion *int64    `json:"schema_version"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type FamilyMembership struct {
	FamilyID *string   `json:"family_id"`
	UserID   *string   `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type SchemaMigration struct {
	Version         int64      `json:"version"`
	Name            string     `json:"name"`
	Filename        string     `json:"filename"`
	Description     *string    `json:"description"`
	AppliedAt       *time.Time `json:"applied_at"`
	Checksum        *string    `json:"checksum"`
	ExecutionTimeMs *int64     `json:"execution_time_ms"`
	MigrationType   *string    `json:"migration_type"`
	AppliedBy       *string    `json:"applied_by"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserSession struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	FamilyID   string    `json:"family_id"`
	UserRole   string    `json:"user_role"`
	CreatedAt  time.Time `json:"created_at"`
	LastActive time.Time `json:"last_active"`
	ExpiresAt  time.Time `json:"expires_at"`
	UserAgent  *string   `json:"user_agent"`
	IpAddress  *string   `json:"ip_address"`
}
