// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package masterdb

import (
	"context"
	"time"
)

type Querier interface {
	CheckUserExists(ctx context.Context, email string) (int64, error)
	CheckUserExistsInFamily(ctx context.Context, userID *string) (int64, error)
	CleanupExpiredSessions(ctx context.Context, expiresAt time.Time) error
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (*Family, error)
	CreateFamilyMembership(ctx context.Context, arg CreateFamilyMembershipParams) (*FamilyMembership, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (*UserSession, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteFamily(ctx context.Context, id string) error
	DeleteFamilyMembership(ctx context.Context, arg DeleteFamilyMembershipParams) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserSession(ctx context.Context, id string) error
	GetFamilyByID(ctx context.Context, id string) (*Family, error)
	GetFamilyByInviteCode(ctx context.Context, inviteCode string) (*Family, error)
	GetFamilyMembership(ctx context.Context, arg GetFamilyMembershipParams) (*FamilyMembership, error)
	GetUserActiveSessions(ctx context.Context, arg GetUserActiveSessionsParams) ([]*UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id string) (*User, error)
	GetUserFamilyInfo(ctx context.Context, userID *string) (*GetUserFamilyInfoRow, error)
	GetUserSession(ctx context.Context, id string) (*UserSession, error)
	ListFamilyMemberships(ctx context.Context, familyID *string) ([]*FamilyMembership, error)
	ListUserMemberships(ctx context.Context, userID *string) ([]*FamilyMembership, error)
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (*Family, error)
	UpdateFamilyMembershipRole(ctx context.Context, arg UpdateFamilyMembershipRoleParams) (*FamilyMembership, error)
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	UpdateUserFamilySessions(ctx context.Context, arg UpdateUserFamilySessionsParams) error
}

var _ Querier = (*Queries)(nil)
