// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package masterdb

import (
	"context"
	"time"
)

type Querier interface {
	CheckMigrationApplied(ctx context.Context, version int64) (int64, error)
	// This query will return 1 if table exists, 0 if not
	// We use a simple approach that works with sqlc
	CheckMigrationsTableExists(ctx context.Context) (int64, error)
	CheckUserExists(ctx context.Context, email string) (int64, error)
	CheckUserExistsInFamily(ctx context.Context, userID *int64) (int64, error)
	CleanupExpiredSessions(ctx context.Context, expiresAt time.Time) error
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (*Family, error)
	CreateFamilyMembership(ctx context.Context, arg CreateFamilyMembershipParams) (*FamilyMembership, error)
	CreateMigrationsTable(ctx context.Context) error
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (*UserSession, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error
	DeleteFamily(ctx context.Context, id int64) error
	DeleteFamilyMembership(ctx context.Context, arg DeleteFamilyMembershipParams) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSession(ctx context.Context, id int64) error
	DeleteUserSessionByToken(ctx context.Context, sessionToken *string) error
	GetAppliedMigrations(ctx context.Context) ([]*GetAppliedMigrationsRow, error)
	// Migration-related queries for master database
	GetCurrentMigrationVersion(ctx context.Context) (int64, error)
	GetFamilyByID(ctx context.Context, id int64) (*Family, error)
	GetFamilyByInviteCode(ctx context.Context, inviteCode string) (*Family, error)
	GetFamilyMembership(ctx context.Context, arg GetFamilyMembershipParams) (*FamilyMembership, error)
	GetUserActiveSessions(ctx context.Context, arg GetUserActiveSessionsParams) ([]*UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id int64) (*User, error)
	GetUserFamilyInfo(ctx context.Context, userID *int64) (*GetUserFamilyInfoRow, error)
	GetUserSession(ctx context.Context, id int64) (*UserSession, error)
	GetUserSessionByToken(ctx context.Context, sessionToken *string) (*UserSession, error)
	ListFamilyMemberships(ctx context.Context, familyID *int64) ([]*FamilyMembership, error)
	ListUserMemberships(ctx context.Context, userID *int64) ([]*FamilyMembership, error)
	RecordMigration(ctx context.Context, arg RecordMigrationParams) error
	RefreshSession(ctx context.Context, arg RefreshSessionParams) error
	RefreshSessionByToken(ctx context.Context, arg RefreshSessionByTokenParams) error
	UpdateFamily(ctx context.Context, arg UpdateFamilyParams) (*Family, error)
	UpdateFamilyMembershipRole(ctx context.Context, arg UpdateFamilyMembershipRoleParams) (*FamilyMembership, error)
	UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error
	UpdateSessionActivityByToken(ctx context.Context, arg UpdateSessionActivityByTokenParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	UpdateUserFamilySessions(ctx context.Context, arg UpdateUserFamilySessionsParams) error
}

var _ Querier = (*Queries)(nil)
